services:

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: dwarf
      # MARIADB_USER: normuser
      # MARIADB_PASSWORD: normpw
      # MARIADB_DATABASE: exmpledb
    ports:
      - "3306:3306"
    volumes:
      - ./Mariadb/volumes:/var/lib/mysql
#Create database mountainhome - > needs to be done at startup

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"

      # start with docker compose up -d

      # cmd(pre 11.0.1)(higher versions then 10.11.6 dont have mysql):
      # docker exec -it mariadb mysql --user=root --password=rootpw

      # cmd: docker exec -it mariadb mariadb -p rootpw

      # adminer runs on localhost:8282
      # server = container_name
      # user = root
      # password = MARIADB_ROOT_PASSWORD